org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21, 1.22)
neo_version=21.1.137
neo_version_range=[21,)
loader_version_range=[1,)

mod_id=screenshot_with_coords
mod_name=Screenshot with Coords
mod_license=Apache 2.0
mod_version=1.0.0+1.21
mod_authors=Liu Dongyu, nullset, ECNUMC
mod_description=Export players' screenshots with their locations and rotations.